#  **********************
#  * MÁQUINA DE VENDING *
#  **********************

# FUNCIÓN DE LECTURA

# FUNCIÓN DE ESCRITURA

# FUNCIÓN DE PEDIDO

# FUNCIÓN DE REPOSICIÓN DE PRODUCTO

# FUNCIÓN DE CAMBIO DE PRECIO

# FUNCIÓN DE REPOSICION DE DINERO
